embeddings {
  tensor_name: "series_id:02450"
  metadata_path: "02450/series_id/metadata.tsv"
  tensor_path: "02450/series_id/tensors.tsv"
}
embeddings {
  tensor_name: "month:02450"
  metadata_path: "02450/month/metadata.tsv"
  tensor_path: "02450/month/tensors.tsv"
}
