embeddings {
  tensor_name: "series_id:01750"
  metadata_path: "01750/series_id/metadata.tsv"
  tensor_path: "01750/series_id/tensors.tsv"
}
embeddings {
  tensor_name: "month:01750"
  metadata_path: "01750/month/metadata.tsv"
  tensor_path: "01750/month/tensors.tsv"
}
